patchelf: Update to version 0.9
Remove patch maxsize.patch already applied upstream.

Add patch Skip-empty-section-fixes-66.patch to prevent errors like:

ERROR: go-cross-1.6.2-r0 do_populate_sysroot_setscene: '('patchelf-uninative',
'--set-interpreter', '/home/user/src/prj/build/tmp/sysroots-uninative/
x86_64-linux/lib/ld-linux-x86-64.so.2', '/home/user/src/prj/build/tmp/
work/x86_64-linux/go-cross/1.6.2-r0/sstate-install-populate_sysroot/x86_64-
linux/usr/bin/aarch64-prj-linux/go')'
failed with exit code 1 and the following output:
cannot find section .rela.dyn

(From OE-Core rev: 3848b2554593fcb8103137916c1474a3ec6558ba)

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>